// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqg3SX8QcyaNRJZU0i4iy7dg7nHw6cHuQ',
    appId: '1:988876277090:web:380aa9fb526a881016583b',
    messagingSenderId: '988876277090',
    projectId: 'pawprint-8a4f4',
    authDomain: 'pawprint-8a4f4.firebaseapp.com',
    storageBucket: 'pawprint-8a4f4.appspot.com',
    measurementId: 'G-WXSXPL2GHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbwRVtL3lgjI7BS1cSQcKmA9vdJbLZyZw',
    appId: '1:988876277090:android:e5a1f01b380129d116583b',
    messagingSenderId: '988876277090',
    projectId: 'pawprint-8a4f4',
    storageBucket: 'pawprint-8a4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVnD7wuYvF634atN_VThaSev2wTzn-S_Y',
    appId: '1:988876277090:ios:605ade0b57dbe34416583b',
    messagingSenderId: '988876277090',
    projectId: 'pawprint-8a4f4',
    storageBucket: 'pawprint-8a4f4.appspot.com',
    iosBundleId: 'com.example.pawprintgp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVnD7wuYvF634atN_VThaSev2wTzn-S_Y',
    appId: '1:988876277090:ios:605ade0b57dbe34416583b',
    messagingSenderId: '988876277090',
    projectId: 'pawprint-8a4f4',
    storageBucket: 'pawprint-8a4f4.appspot.com',
    iosBundleId: 'com.example.pawprintgp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqg3SX8QcyaNRJZU0i4iy7dg7nHw6cHuQ',
    appId: '1:988876277090:web:46488ce579e4bd0016583b',
    messagingSenderId: '988876277090',
    projectId: 'pawprint-8a4f4',
    authDomain: 'pawprint-8a4f4.firebaseapp.com',
    storageBucket: 'pawprint-8a4f4.appspot.com',
    measurementId: 'G-26N61JN3SF',
  );
}
